version: '3.9'
services:
  redis:
    image: redis
    container_name: redis
    ports: 
      - 6379:6379
    volumes:
      - "./data/redis:/data"
      - "./config/redis.conf:/redis.conf"
    command: redis-server /redis.conf
  k6:
    image: loadimpact/k6
    container_name: k6
    volumes:
      - "./scripts:/scripts"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
  influxdb: 
    image: influxdb:1.8.10
    container_name: influxdb
    ports: 
      - 8086:8086
    volumes:
      - "./data/influxdb:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: 
      - 3000:3000
    volumes:
      - "./data/gafana:/var/lib/gafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=P@ssw0rd
      - MARIADB_DATABASE=test
    ports: 
      - 3307:3306
    volumes:
      - "./data/mariadb:/var/lib/mysql"